### ISSUE TITLE
Conditional execution of a function

### ISSUE THREAD

**Issue by andkov** [andkov/trajectory-change-viewer#1]
@wibeasley, I am trying to create a function that breaks gracefully when a certain condition is not met, specifically when a character values pass to the argument does not belong to a set. 

Here's my solution

```r
string_1 <- "a"
string_2 <- "y"
string_3 <- NULL 

pool  <- c("a", "b")

foo <- function(x){
  if( any(pool==x)){
   toupper(x)
  }else{
    print("Entry is not valid")
  }
}

string_1 %>% foo()
string_2 %>% foo()
string_3 %>% foo()
```

However, I wonder if there is an easier way or doing it with `checkmate`? Any suggestions?

**Comment by wibeasley** [comment]
Yeah, I think [`checkmate::check_subset()`](https://mllg.github.io/checkmate/reference/checkSubset.html) fits your need exactly.  But also look at `test_subset()` (which returns T/F) and `assert_subset()` which returns text messages.

```r
foo <- function (x){
  checkmate::assert_subset(
    x         = x, 
    choices   = pool, 
    empty.ok  = FALSE
  )
  x
}
```

produces
```r
> string_1 |> foo()
[1] "a"

> string_2 |> foo()
 Error in foo(string_2) : 
  Assertion on 'x' failed: Must be a subset of {'a','b'}, but is {'y'}. 

> string_3 |> foo()
 Error in foo(string_3) : 
  Assertion on 'x' failed: Must be a subset of {'a','b'}, not empty. 
```

I know you'd returned a string for bad values, but I typically prefer errors.  You don't want the user to have to parse the returned value and decide if it was an error or not.

**Comment by andkov** [comment]
thanks, @wibeasley , that's exactly what I need and it appears to work more conveniently (to me) than character(0)

I agree, `checkmate::assert_subset` is more informative. I was going for a string because I thought it will be more descriptive, but I am convinced otherwise with `assert_subset` behavior. 

Thank! I plan on turning this display into a Shiny, which I would like to use to learn tests and function breaks better.

**Comment by wibeasley** [comment]
This might be helpful.  I know Hadley's written similar things in books, but I'm not finding them quickly. https://youtu.be/Qne86lxjgtg?t=1731
